---
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: "30 0 * * *"

jobs:
  test-setup:
    env:
      OCAML_VARIANT: ocaml-variants.5.2.0+ox
    strategy:
      fail-fast: false
      matrix:
        # For info on the OS versions, architecture, etc., see
        # https://docs.github.com/en/actions/using-github-hosted-runners/using-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories
        os: [ubuntu-latest, ubuntu-24.04-arm, macos-13, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Run Test OxCaml action
        uses: ./.github/actions/test-oxcaml
        with:
          ocaml-compiler: ${{ env.OCAML_VARIANT }}
